pool:
  name: Default
  demands:
  - MSBuild

variables:
  BuildConfiguration: 'Release'
  configuration: release
  platform: x64
  zipname: 'UserParameters_$(PROD_VER)'

steps:
  - task: VSBuild@1
    inputs:
      solution: '**\*.sln'
      msbuildArchitecture: 'x64'

  - task: PowerShell@2
    displayName: 'PowerShell Script'
    inputs:
      targetType: filePath
      filePath: ./version.ps1

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)'
      contents: |
        main.js
        palette.html
        UserParameters.dll
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(zipname).zip'
      replaceExistingArchive: true
  
  - task: GitHubRelease@1
    inputs:
      gitHubConnection: "GitHub"
      repositoryName: '$(Build.Repository.Name)'
      action: 'create'
      target: '$(Build.SourceVersion)'
      tagSource: 'userSpecifiedTag'
      tag: '$(PROD_VER)'
      isDraft: true
      changeLogCompareToRelease: 'lastFullRelease'
      changeLogType: 'commitBased'
      assets: '$(Build.ArtifactStagingDirectory)/$(zipname).zip' 